package br.iteratorsystems.cps.entities;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name="bairro"
    ,schema="tabelas"
)
public class BAIRRO  implements java.io.Serializable, EntityAble {
     
	 private static final long serialVersionUID = 51543881036318619L;
	 private BAIRROID id;
     private LOCALIDADE localidade;
     private String bairro;
     private String abrevbairro;

    public BAIRRO() {
    }
	
    public BAIRRO(BAIRROID id, LOCALIDADE localidade, String bairro) {
        this.id = id;
        this.localidade = localidade;
        this.bairro = bairro;
    }
    public BAIRRO(BAIRROID id, LOCALIDADE localidade, String bairro, String abrevbairro) {
       this.id = id;
       this.localidade = localidade;
       this.bairro = bairro;
       this.abrevbairro = abrevbairro;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="uf", column=@Column(name="uf", nullable=false, length=2) ), 
        @AttributeOverride(name="idLocalidade", column=@Column(name="id_localidade", nullable=false, length=6) ), 
        @AttributeOverride(name="idBairro", column=@Column(name="id_bairro", nullable=false, length=6) ) } )
    public BAIRROID getId() {
        return this.id;
    }
    
    public void setId(BAIRROID id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_localidade", nullable=false, insertable=false, updatable=false)
    public LOCALIDADE getLocalidade() {
        return this.localidade;
    }
    
    public void setLocalidade(LOCALIDADE localidade) {
        this.localidade = localidade;
    }
    
    @Column(name="bairro", nullable=false, length=60)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    
    @Column(name="abrevbairro", length=30)
    public String getAbrevbairro() {
        return this.abrevbairro;
    }
    
    public void setAbrevbairro(String abrevbairro) {
        this.abrevbairro = abrevbairro;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((abrevbairro == null) ? 0 : abrevbairro.hashCode());
		result = prime * result + ((bairro == null) ? 0 : bairro.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((localidade == null) ? 0 : localidade.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof BAIRRO))
			return false;
		BAIRRO other = (BAIRRO) obj;
		if (abrevbairro == null) {
			if (other.abrevbairro != null)
				return false;
		} else if (!abrevbairro.equals(other.abrevbairro))
			return false;
		if (bairro == null) {
			if (other.bairro != null)
				return false;
		} else if (!bairro.equals(other.bairro))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (localidade == null) {
			if (other.localidade != null)
				return false;
		} else if (!localidade.equals(other.localidade))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "BAIRRO [abrevbairro=" + abrevbairro + ", bairro=" + bairro
				+ ", id=" + id + ", localidade=" + localidade + "]";
	}
    
    
}