package br.iteratorsystems.cps.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * ContatoLojaId generated by hbm2java
 */
@Embeddable
public class CONTATOLOJAID implements java.io.Serializable, EntityAble {

	 private static final long serialVersionUID = -5180240306926430112L;
     private Integer idRede;
     private Integer idLoja;

    public CONTATOLOJAID() {
    }

    public CONTATOLOJAID(Integer idRede, Integer idLoja) {
       this.idRede = idRede;
       this.idLoja = idLoja;
    }
   

    @Column(name="id_rede", nullable=false)
    public Integer getIdRede() {
        return this.idRede;
    }
    
    public void setIdRede(Integer idRede) {
        this.idRede = idRede;
    }

    @Column(name="id_loja", nullable=false)
    public Integer getIdLoja() {
        return this.idLoja;
    }
    
    public void setIdLoja(Integer idLoja) {
        this.idLoja = idLoja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CONTATOLOJAID) ) return false;
		 CONTATOLOJAID castOther = ( CONTATOLOJAID ) other; 
         
		 return (this.getIdRede()==castOther.getIdRede())
 && (this.getIdLoja()==castOther.getIdLoja());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRede();
         result = 37 * result + this.getIdLoja();
         return result;
   }

@Override
public String toString() {
	return "CONTATOLOJAID [idLoja=" + idLoja + ", idRede=" + idRede + "]";
}  
   
   
}