package br.iteratorsystems.cps.entities;



import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Localizacao generated by hbm2java
 */
@Entity
@Table(name="localizacao"
    ,schema="tabelas"
)
public class Localizacao  implements java.io.Serializable {
     
 	 private static final long serialVersionUID = -4039480426713396518L;
	 private BigInteger id;
     private String country;
     private String language;
     private String iso2;
     private String region1;
     private String region2;
     private String region3;
     private String region4;
     private String zip;
     private String city;
     private String area1;
     private String area2;
     private Double lat;
     private Double lng;
     private String tz;
     private String utc;
     private String dst;

    public Localizacao() {
    }

    public Localizacao(BigInteger id, String country, String language, String iso2, String region1, String region2, String region3, String region4, String zip, String city, String area1, String area2, Double lat, Double lng, String tz, String utc, String dst) {
       this.id = id;
       this.country = country;
       this.language = language;
       this.iso2 = iso2;
       this.region1 = region1;
       this.region2 = region2;
       this.region3 = region3;
       this.region4 = region4;
       this.zip = zip;
       this.city = city;
       this.area1 = area1;
       this.area2 = area2;
       this.lat = lat;
       this.lng = lng;
       this.tz = tz;
       this.utc = utc;
       this.dst = dst;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(BigInteger id) {
        this.id = id;
    }
    
    @Column(name="country", nullable=false, length=2)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="language", nullable=false, length=2)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    @Column(name="iso2", nullable=false, length=6)
    public String getIso2() {
        return this.iso2;
    }
    
    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }
    
    @Column(name="region1", nullable=false, length=60)
    public String getRegion1() {
        return this.region1;
    }
    
    public void setRegion1(String region1) {
        this.region1 = region1;
    }
    
    @Column(name="region2", nullable=false, length=60)
    public String getRegion2() {
        return this.region2;
    }
    
    public void setRegion2(String region2) {
        this.region2 = region2;
    }
    
    @Column(name="region3", nullable=false, length=60)
    public String getRegion3() {
        return this.region3;
    }
    
    public void setRegion3(String region3) {
        this.region3 = region3;
    }
    
    @Column(name="region4", nullable=false, length=60)
    public String getRegion4() {
        return this.region4;
    }
    
    public void setRegion4(String region4) {
        this.region4 = region4;
    }
    
    @Column(name="zip", nullable=false, length=10)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    
    @Column(name="city", nullable=false, length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="area1", nullable=false, length=80)
    public String getArea1() {
        return this.area1;
    }
    
    public void setArea1(String area1) {
        this.area1 = area1;
    }
    
    @Column(name="area2", nullable=false, length=80)
    public String getArea2() {
        return this.area2;
    }
    
    public void setArea2(String area2) {
        this.area2 = area2;
    }
    
    @Column(name="lat", nullable=false, precision=17, scale=17)
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    
    @Column(name="lng", nullable=false, precision=17, scale=17)
    public Double getLng() {
        return this.lng;
    }
    
    public void setLng(Double lng) {
        this.lng = lng;
    }
    
    @Column(name="tz", nullable=false, length=30)
    public String getTz() {
        return this.tz;
    }
    
    public void setTz(String tz) {
        this.tz = tz;
    }
    
    @Column(name="utc", nullable=false, length=10)
    public String getUtc() {
        return this.utc;
    }
    
    public void setUtc(String utc) {
        this.utc = utc;
    }
    
    @Column(name="dst", nullable=false, length=1)
    public String getDst() {
        return this.dst;
    }
    
    public void setDst(String dst) {
        this.dst = dst;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Localizacao [area1=" + area1 + ", area2=" + area2 + ", city="
				+ city + ", country=" + country + ", dst=" + dst + ", id=" + id
				+ ", iso2=" + iso2 + ", language=" + language + ", lat=" + lat
				+ ", lng=" + lng + ", region1=" + region1 + ", region2="
				+ region2 + ", region3=" + region3 + ", region4=" + region4
				+ ", tz=" + tz + ", utc=" + utc + ", zip=" + zip + "]";
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((area1 == null) ? 0 : area1.hashCode());
		result = prime * result + ((area2 == null) ? 0 : area2.hashCode());
		result = prime * result + ((city == null) ? 0 : city.hashCode());
		result = prime * result + ((country == null) ? 0 : country.hashCode());
		result = prime * result + ((dst == null) ? 0 : dst.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((iso2 == null) ? 0 : iso2.hashCode());
		result = prime * result
				+ ((language == null) ? 0 : language.hashCode());
		result = prime * result + ((lat == null) ? 0 : lat.hashCode());
		result = prime * result + ((lng == null) ? 0 : lng.hashCode());
		result = prime * result + ((region1 == null) ? 0 : region1.hashCode());
		result = prime * result + ((region2 == null) ? 0 : region2.hashCode());
		result = prime * result + ((region3 == null) ? 0 : region3.hashCode());
		result = prime * result + ((region4 == null) ? 0 : region4.hashCode());
		result = prime * result + ((tz == null) ? 0 : tz.hashCode());
		result = prime * result + ((utc == null) ? 0 : utc.hashCode());
		result = prime * result + ((zip == null) ? 0 : zip.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Localizacao))
			return false;
		Localizacao other = (Localizacao) obj;
		if (area1 == null) {
			if (other.area1 != null)
				return false;
		} else if (!area1.equals(other.area1))
			return false;
		if (area2 == null) {
			if (other.area2 != null)
				return false;
		} else if (!area2.equals(other.area2))
			return false;
		if (city == null) {
			if (other.city != null)
				return false;
		} else if (!city.equals(other.city))
			return false;
		if (country == null) {
			if (other.country != null)
				return false;
		} else if (!country.equals(other.country))
			return false;
		if (dst == null) {
			if (other.dst != null)
				return false;
		} else if (!dst.equals(other.dst))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (iso2 == null) {
			if (other.iso2 != null)
				return false;
		} else if (!iso2.equals(other.iso2))
			return false;
		if (language == null) {
			if (other.language != null)
				return false;
		} else if (!language.equals(other.language))
			return false;
		if (lat == null) {
			if (other.lat != null)
				return false;
		} else if (!lat.equals(other.lat))
			return false;
		if (lng == null) {
			if (other.lng != null)
				return false;
		} else if (!lng.equals(other.lng))
			return false;
		if (region1 == null) {
			if (other.region1 != null)
				return false;
		} else if (!region1.equals(other.region1))
			return false;
		if (region2 == null) {
			if (other.region2 != null)
				return false;
		} else if (!region2.equals(other.region2))
			return false;
		if (region3 == null) {
			if (other.region3 != null)
				return false;
		} else if (!region3.equals(other.region3))
			return false;
		if (region4 == null) {
			if (other.region4 != null)
				return false;
		} else if (!region4.equals(other.region4))
			return false;
		if (tz == null) {
			if (other.tz != null)
				return false;
		} else if (!tz.equals(other.tz))
			return false;
		if (utc == null) {
			if (other.utc != null)
				return false;
		} else if (!utc.equals(other.utc))
			return false;
		if (zip == null) {
			if (other.zip != null)
				return false;
		} else if (!zip.equals(other.zip))
			return false;
		return true;
	}
    
}


