package br.iteratorsystems.cps.entities;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * LOJA generated by hbm2java
 */
@Entity
@Table(name = "loja", schema = "tabelas")
public class LOJA implements java.io.Serializable, EntityAble {

	private static final long serialVersionUID = 1L;
	private LOJAID id;
	private REDE rede;
	private String razaosocial;
	private String nomefantasia;
	private String cnpj;
	private String inscricaoestadual;
	private String inscricaomunicipal;
	private String nomedoresponsavelpelaloja;
	private char tipodevenda;
	private String pais;
	private String estado;
	private String cidade;
	private String bairro;
	private String logradouro;
	private String numero;
	private String complemento;
	private String cep;
	private Date dataultimamodificacao;
	private String telCom;
	private String dddCelCom;
	private String telCelCom;
	private String dddFax;
	private String telFax;
	private String email;
	private String homepage;

	public LOJA() {
	}

	public LOJA(LOJAID id, REDE rede, String razaosocial, String nomefantasia,
			String cnpj, char tipodevenda, String pais, String estado,
			String cidade, String bairro, String logradouro, String numero,
			String cep, Date dataultimamodificacao) {
		this.id = id;
		this.rede = rede;
		this.razaosocial = razaosocial;
		this.nomefantasia = nomefantasia;
		this.cnpj = cnpj;
		this.tipodevenda = tipodevenda;
		this.pais = pais;
		this.estado = estado;
		this.cidade = cidade;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.numero = numero;
		this.cep = cep;
		this.dataultimamodificacao = dataultimamodificacao;
	}

	public LOJA(LOJAID id, REDE rede, String razaosocial, String nomefantasia,
			String cnpj, String inscricaoestadual, String inscricaomunicipal,
			String nomedoresponsavelpelaloja, char tipodevenda, String pais,
			String estado, String cidade, String bairro, String logradouro,
			String numero, String complemento, String cep,
			Date dataultimamodificacao, String telCom, String dddCelCom,
			String telCelCom, String dddFax, String telFax, String email,
			String homepage) {
		this.id = id;
		this.rede = rede;
		this.razaosocial = razaosocial;
		this.nomefantasia = nomefantasia;
		this.cnpj = cnpj;
		this.inscricaoestadual = inscricaoestadual;
		this.inscricaomunicipal = inscricaomunicipal;
		this.nomedoresponsavelpelaloja = nomedoresponsavelpelaloja;
		this.tipodevenda = tipodevenda;
		this.pais = pais;
		this.estado = estado;
		this.cidade = cidade;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
		this.cep = cep;
		this.dataultimamodificacao = dataultimamodificacao;
		this.telCom = telCom;
		this.dddCelCom = dddCelCom;
		this.telCelCom = telCelCom;
		this.dddFax = dddFax;
		this.telFax = telFax;
		this.email = email;
		this.homepage = homepage;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idLoja", column = @Column(name = "id_loja", nullable = false)),
			@AttributeOverride(name = "idRede", column = @Column(name = "id_rede", nullable = false)) })
	public LOJAID getId() {
		return this.id;
	}

	public void setId(LOJAID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rede", nullable = false, insertable = false, updatable = false)
	public REDE getRede() {
		return this.rede;
	}

	public void setRede(REDE rede) {
		this.rede = rede;
	}

	@Column(name = "razaosocial", nullable = false, length = 60)
	public String getRazaosocial() {
		return this.razaosocial;
	}

	public void setRazaosocial(String razaosocial) {
		this.razaosocial = razaosocial;
	}

	@Column(name = "nomefantasia", nullable = false, length = 60)
	public String getNomefantasia() {
		return this.nomefantasia;
	}

	public void setNomefantasia(String nomefantasia) {
		this.nomefantasia = nomefantasia;
	}

	@Column(name = "cnpj", nullable = false, length = 20)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;//.replace(".","").replace("/","").replace("-","");
	}

	@Column(name = "inscricaoestadual", length = 20)
	public String getInscricaoestadual() {
		return this.inscricaoestadual;
	}

	public void setInscricaoestadual(String inscricaoestadual) {
		this.inscricaoestadual = inscricaoestadual;
	}

	@Column(name = "inscricaomunicipal", length = 20)
	public String getInscricaomunicipal() {
		return this.inscricaomunicipal;
	}

	public void setInscricaomunicipal(String inscricaomunicipal) {
		this.inscricaomunicipal = inscricaomunicipal;
	}

	@Column(name = "nomedoresponsavelpelaloja", length = 30)
	public String getNomedoresponsavelpelaloja() {
		return this.nomedoresponsavelpelaloja;
	}

	public void setNomedoresponsavelpelaloja(String nomedoresponsavelpelaloja) {
		this.nomedoresponsavelpelaloja = nomedoresponsavelpelaloja;
	}

	@Column(name = "tipodevenda", nullable = false, length = 1)
	public char getTipodevenda() {
		return this.tipodevenda;
	}

	public void setTipodevenda(char tipodevenda) {
		this.tipodevenda = tipodevenda;
	}

	@Column(name = "pais", nullable = false, length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "estado", nullable = false, length = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "cidade", nullable = false, length = 50)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "bairro", nullable = false, length = 50)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "logradouro", nullable = false, length = 50)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero", nullable = false, length = 6)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 20)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "cep", nullable = false, length = 9)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;//.replace("-","");
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataultimamodificacao", nullable = false, length = 13)
	public Date getDataultimamodificacao() {
		return this.dataultimamodificacao;
	}

	public void setDataultimamodificacao(Date dataultimamodificacao) {
		this.dataultimamodificacao = dataultimamodificacao;
	}

	@Column(name = "tel_com", length = 13)
	public String getTelCom() {
		return this.telCom;
	}

	public void setTelCom(String telCom) {
		this.telCom = telCom;
	}

	@Column(name = "ddd_cel_com", length = 3)
	public String getDddCelCom() {
		return this.dddCelCom;
	}

	public void setDddCelCom(String dddCelCom) {
		this.dddCelCom = dddCelCom;
	}

	@Column(name = "tel_cel_com", length = 8)
	public String getTelCelCom() {
		return this.telCelCom;
	}

	public void setTelCelCom(String telCelCom) {
		this.telCelCom = telCelCom;//.replace("-","");
	}

	@Column(name = "ddd_fax", length = 3)
	public String getDddFax() {
		return this.dddFax;
	}

	public void setDddFax(String dddFax) {
		this.dddFax = dddFax;
	}

	@Column(name = "tel_fax", length = 8)
	public String getTelFax() {
		return this.telFax;
	}

	public void setTelFax(String telFax) {
		this.telFax = telFax;//.replace("-","");
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "homepage", length = 100)
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bairro == null) ? 0 : bairro.hashCode());
		result = prime * result + ((cep == null) ? 0 : cep.hashCode());
		result = prime * result + ((cidade == null) ? 0 : cidade.hashCode());
		result = prime * result + ((cnpj == null) ? 0 : cnpj.hashCode());
		result = prime * result
				+ ((complemento == null) ? 0 : complemento.hashCode());
		result = prime
				* result
				+ ((dataultimamodificacao == null) ? 0 : dataultimamodificacao
						.hashCode());
		result = prime * result
				+ ((dddCelCom == null) ? 0 : dddCelCom.hashCode());
		result = prime * result + ((dddFax == null) ? 0 : dddFax.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((estado == null) ? 0 : estado.hashCode());
		result = prime * result
				+ ((homepage == null) ? 0 : homepage.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime
				* result
				+ ((inscricaoestadual == null) ? 0 : inscricaoestadual
						.hashCode());
		result = prime
				* result
				+ ((inscricaomunicipal == null) ? 0 : inscricaomunicipal
						.hashCode());
		result = prime * result
				+ ((logradouro == null) ? 0 : logradouro.hashCode());
		result = prime
				* result
				+ ((nomedoresponsavelpelaloja == null) ? 0
						: nomedoresponsavelpelaloja.hashCode());
		result = prime * result
				+ ((nomefantasia == null) ? 0 : nomefantasia.hashCode());
		result = prime * result + ((numero == null) ? 0 : numero.hashCode());
		result = prime * result + ((pais == null) ? 0 : pais.hashCode());
		result = prime * result
				+ ((razaosocial == null) ? 0 : razaosocial.hashCode());
		result = prime * result + ((rede == null) ? 0 : rede.hashCode());
		result = prime * result
				+ ((telCelCom == null) ? 0 : telCelCom.hashCode());
		result = prime * result + ((telCom == null) ? 0 : telCom.hashCode());
		result = prime * result + ((telFax == null) ? 0 : telFax.hashCode());
		result = prime * result + tipodevenda;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof LOJA))
			return false;
		LOJA other = (LOJA) obj;
		if (bairro == null) {
			if (other.bairro != null)
				return false;
		} else if (!bairro.equals(other.bairro))
			return false;
		if (cep == null) {
			if (other.cep != null)
				return false;
		} else if (!cep.equals(other.cep))
			return false;
		if (cidade == null) {
			if (other.cidade != null)
				return false;
		} else if (!cidade.equals(other.cidade))
			return false;
		if (cnpj == null) {
			if (other.cnpj != null)
				return false;
		} else if (!cnpj.equals(other.cnpj))
			return false;
		if (complemento == null) {
			if (other.complemento != null)
				return false;
		} else if (!complemento.equals(other.complemento))
			return false;
		if (dataultimamodificacao == null) {
			if (other.dataultimamodificacao != null)
				return false;
		} else if (!dataultimamodificacao.equals(other.dataultimamodificacao))
			return false;
		if (dddCelCom == null) {
			if (other.dddCelCom != null)
				return false;
		} else if (!dddCelCom.equals(other.dddCelCom))
			return false;
		if (dddFax == null) {
			if (other.dddFax != null)
				return false;
		} else if (!dddFax.equals(other.dddFax))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (!estado.equals(other.estado))
			return false;
		if (homepage == null) {
			if (other.homepage != null)
				return false;
		} else if (!homepage.equals(other.homepage))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (inscricaoestadual == null) {
			if (other.inscricaoestadual != null)
				return false;
		} else if (!inscricaoestadual.equals(other.inscricaoestadual))
			return false;
		if (inscricaomunicipal == null) {
			if (other.inscricaomunicipal != null)
				return false;
		} else if (!inscricaomunicipal.equals(other.inscricaomunicipal))
			return false;
		if (logradouro == null) {
			if (other.logradouro != null)
				return false;
		} else if (!logradouro.equals(other.logradouro))
			return false;
		if (nomedoresponsavelpelaloja == null) {
			if (other.nomedoresponsavelpelaloja != null)
				return false;
		} else if (!nomedoresponsavelpelaloja
				.equals(other.nomedoresponsavelpelaloja))
			return false;
		if (nomefantasia == null) {
			if (other.nomefantasia != null)
				return false;
		} else if (!nomefantasia.equals(other.nomefantasia))
			return false;
		if (numero == null) {
			if (other.numero != null)
				return false;
		} else if (!numero.equals(other.numero))
			return false;
		if (pais == null) {
			if (other.pais != null)
				return false;
		} else if (!pais.equals(other.pais))
			return false;
		if (razaosocial == null) {
			if (other.razaosocial != null)
				return false;
		} else if (!razaosocial.equals(other.razaosocial))
			return false;
		if (rede == null) {
			if (other.rede != null)
				return false;
		} else if (!rede.equals(other.rede))
			return false;
		if (telCelCom == null) {
			if (other.telCelCom != null)
				return false;
		} else if (!telCelCom.equals(other.telCelCom))
			return false;
		if (telCom == null) {
			if (other.telCom != null)
				return false;
		} else if (!telCom.equals(other.telCom))
			return false;
		if (telFax == null) {
			if (other.telFax != null)
				return false;
		} else if (!telFax.equals(other.telFax))
			return false;
		if (tipodevenda != other.tipodevenda)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "LOJA [bairro=" + bairro + ", cep=" + cep + ", cidade=" + cidade
				+ ", cnpj=" + cnpj + ", complemento=" + complemento
				+ ", dataultimamodificacao=" + dataultimamodificacao
				+ ", dddCelCom=" + dddCelCom + ", dddFax=" + dddFax
				+ ", email=" + email + ", estado=" + estado + ", homepage="
				+ homepage + ", id=" + id + ", inscricaoestadual="
				+ inscricaoestadual + ", inscricaomunicipal="
				+ inscricaomunicipal + ", logradouro=" + logradouro
				+ ", nomedoresponsavelpelaloja=" + nomedoresponsavelpelaloja
				+ ", nomefantasia=" + nomefantasia + ", numero=" + numero
				+ ", pais=" + pais + ", razaosocial=" + razaosocial + ", rede="
				+ rede + ", telCelCom=" + telCelCom + ", telCom=" + telCom
				+ ", telFax=" + telFax + ", tipodevenda=" + tipodevenda + "]";
	}

	
}
