package br.iteratorsystems.cps.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * ProdutoId generated by hbm2java
 */
@Embeddable
public class Tabelas_ProdutoId  implements java.io.Serializable,EntityAble {


	 private static final long serialVersionUID = 8817585550944242296L;
	 private String codigoBarras;
     private Integer idLoja;
     private Integer idRede;

    public Tabelas_ProdutoId() {
    }

    public Tabelas_ProdutoId(String codigoBarras, Integer idLoja, Integer idRede) {
       this.codigoBarras = codigoBarras;
       this.idLoja = idLoja;
       this.idRede = idRede;
    }
   

    @Column(name="codigo_barras", nullable=false, length=20)
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    @Column(name="id_loja", nullable=false)
    public Integer getIdLoja() {
        return this.idLoja;
    }
    
    public void setIdLoja(Integer idLoja) {
        this.idLoja = idLoja;
    }

    @Column(name="id_rede", nullable=false)
    public Integer getIdRede() {
        return this.idRede;
    }
    
    public void setIdRede(Integer idRede) {
        this.idRede = idRede;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Tabelas_ProdutoId) ) return false;
		 Tabelas_ProdutoId castOther = ( Tabelas_ProdutoId ) other; 
         
		 return ( (this.getCodigoBarras()==castOther.getCodigoBarras()) || ( this.getCodigoBarras()!=null && castOther.getCodigoBarras()!=null && this.getCodigoBarras().equals(castOther.getCodigoBarras()) ) )
 && (this.getIdLoja()==castOther.getIdLoja())
 && (this.getIdRede()==castOther.getIdRede());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodigoBarras() == null ? 0 : this.getCodigoBarras().hashCode() );
         result = 37 * result + this.getIdLoja();
         result = 37 * result + this.getIdRede();
         return result;
   }   
}