package br.iteratorsystems.cps.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * Tabelas_EnderecoId generated by hbm2java
 */
@Embeddable
public class Tabelas_EnderecoId implements java.io.Serializable, EntityAble {

	private static final long serialVersionUID = -2195786669229991261L;
	
	private int id;
	private int idUsuario;

	public Tabelas_EnderecoId() {}
	
	public Tabelas_EnderecoId(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Tabelas_EnderecoId(int idEndereco, int idUsuario) {
		this.id = idEndereco;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_endereco", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Tabelas_EnderecoId))
			return false;
		Tabelas_EnderecoId castOther = (Tabelas_EnderecoId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

	@Override
	public String toString() {
		return "Tabelas_EnderecoId [idEndereco=" + id + ", idUsuario="
				+ idUsuario + "]";
	}
	

}
