package br.iteratorsystems.cps.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.iteratorsystems.cps.interfaces.EntityAble;

/**
 * BairroId generated by hbm2java
 */
@Embeddable
public class Tabelas_BairroId  implements java.io.Serializable, EntityAble {
    
	 private static final long serialVersionUID = 4325650396760923819L;
	 private String uf;
     private String idLocalidade;
     private String idBairro;

    public Tabelas_BairroId() {
    }

    public Tabelas_BairroId(String uf, String idLocalidade, String idBairro) {
       this.uf = uf;
       this.idLocalidade = idLocalidade;
       this.idBairro = idBairro;
    }

    @Column(name="uf", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    @Column(name="id_localidade", nullable=false, length=6)
    public String getIdLocalidade() {
        return this.idLocalidade;
    }
    
    public void setIdLocalidade(String idLocalidade) {
        this.idLocalidade = idLocalidade;
    }

    @Column(name="id_bairro", nullable=false, length=6)
    public String getIdBairro() {
        return this.idBairro;
    }
    
    public void setIdBairro(String idBairro) {
        this.idBairro = idBairro;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Tabelas_BairroId) ) return false;
		 Tabelas_BairroId castOther = ( Tabelas_BairroId ) other; 
         
		 return ( (this.getUf()==castOther.getUf()) || ( this.getUf()!=null && castOther.getUf()!=null && this.getUf().equals(castOther.getUf()) ) )
 && ( (this.getIdLocalidade()==castOther.getIdLocalidade()) || ( this.getIdLocalidade()!=null && castOther.getIdLocalidade()!=null && this.getIdLocalidade().equals(castOther.getIdLocalidade()) ) )
 && ( (this.getIdBairro()==castOther.getIdBairro()) || ( this.getIdBairro()!=null && castOther.getIdBairro()!=null && this.getIdBairro().equals(castOther.getIdBairro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUf() == null ? 0 : this.getUf().hashCode() );
         result = 37 * result + ( getIdLocalidade() == null ? 0 : this.getIdLocalidade().hashCode() );
         result = 37 * result + ( getIdBairro() == null ? 0 : this.getIdBairro().hashCode() );
         return result;
   }

@Override
public String toString() {
	return "Tabelas_BairroId [idBairro=" + idBairro + ", idLocalidade=" + idLocalidade
			+ ", uf=" + uf + "]";
}  
   
   
}